@startuml
actor Клиент as user
participant Gateway as gateway
participant Hub as hub
participant Облако as cloud

user -> gateway: Запрос на получение данных в облаке
gateway -> hub: Запрос на получение данных
hub -> gateway: Данные
gateway -> cloud: Данные
cloud --> user: Получение данных из облака
@enduml
