networks:
  kafka-net:
    name: kafka-net
    driver: bridge
  api-net:
    name: api-net
    driver: bridge

services:

  verifier:
    container_name: main-manager-output
    networks:
      - kafka-net
    build:
      context: .
      dockerfile: Dockerfile
