networks:
  kafka-net:
    name: kafka-net
    driver: bridge

services:
  manager-input:
    container_name: manager-input
    networks:
      - kafka-net
    ports:
      - 8081:8081
    build:
      context: .
      dockerfile: Dockerfile
