@startuml

skinparam arrowthickness 3
skinparam defaultFontName Arial
skinparam defaultFontSize 18
skinparam roundCorner 50

legend right
    |Цвет| Описание |
    |<#green>| Доверенный компонент|
    |<#orange>| Повышающий доверие компонент|
    |<#red>| Недоверенный компонент|
endlegend

cloud Облако as cloud
actor Клиент as user
rectangle DeviceAuth as auth #line:Green;line.bold
rectangle Hub as hub #line:Red;line.bold
rectangle ManagerOutput as out #line:Orange;line.bold
rectangle ManagerInput as in #line:Orange;line.bold
rectangle ClientAuth as auth2 #line:green;line.bold
rectangle Storage as storage #line:red;line.bold
circle Девайс as device1

user --[#red]> in: Запрос данных в облако
in --[#Green]> auth2: Аутентификация клиента
auth2 --[#Green]>in: Ответ
in --[#Green]> out: Запрос данных в облако
out --[#Red]> storage: Запрос получения данных
storage --[#Red]> out: Данные
out --[#Green]> cloud : Данные
device1 --[#red]> hub : Данные
hub --[#Red]> storage: Данные устройств
out --[#Green]> auth : Аутентификация устройств
auth --[#Green]> out : Ответ
user -..> cloud : Получить данные
cloud -..> user : Данные
@endumls