@startuml
title "Базовый сценарий. Передача данных ключевых девайсов"
actor Клиент as user
database Облако as cloud
participant ClientAuth as auth2
participant ManagerInput as in
participant verifier as auth
participant MainManagerOutput as out
database MainStorage as storage
participant MainHub as hub
entity MainDevice as device

group Непрерывная передача данных
device -> hub: Данные
hub -> storage: Данные
end

group Запрос данных в облако
user -> in: Запрос получения данных в облако
in -> auth2: Аутентификация клиента
in <- auth2: Ответ
in -> out: Запрос отправки данных в облако
out -> storage: Запрос получения данных
out <- storage: Данные
out -> auth: Аутентификация устройств
out <- auth: Ответ
out -> cloud: Данные
end
@enduml