@startuml

skinparam arrowthickness 3
skinparam defaultFontName Arial
skinparam defaultFontSize 18
skinparam roundCorner 50

legend right
    |Цвет| Описание |
    |<#green>| Доверенный компонент|
    |<#orange>| Повышающий доверие компонент|
    |<#red>| Недоверенный компонент|
endlegend

cloud Облако as cloud
actor Клиент as user


rectangle "Шлюз" #line.dashed{
    

    rectangle Hub as hub #line:Red;line.bold
    rectangle ManagerOutput as out #line:Red;line.bold
    rectangle Storage as storage #line:red;line.bold

    rectangle ClientStorage as cs #line:red;line.bold
    rectangle ClientAuth as auth2 #line:Orange;line.bold

    rectangle ManagerInput as in #line:Orange;line.bold

    rectangle Verifier as verifier #line:Orange;line.bold
    rectangle DeviceStorage as ds #line:red;line.bold
    rectangle MainManagerOutput as mainOut #line:Orange;line.bold
    rectangle MainStorage as mainStorage #line:red;line.bold
    rectangle MainHub as mainHub #line:Red;line.bold
} 


    (КритическийДевайс) as mainDevice #green
    (ПлохойДевайс) as angryDevice2 #red
    (Девайс) as device #green
    (ПлохойДевайс) as angryDevice1 #red

    rectangle "Среда передачи данных" as net #line:Red;line.bold

    angryDevice2 -[#Red]-> net
    mainDevice -[#green]-> net
    net -[#red]-> mainHub


    device -[#green]-> net
    angryDevice1 -[#Red]-> net
    net -[#red]-> hub



mainHub --[#Red]> mainStorage
hub --[#Red]> storage
user -[#red]-> in
in -[#Green]-> auth2
auth2 -[#Green]-> cs
cs .[#Red].> auth2
auth2 .[#Green].>in
in --[#Green]> mainOut
mainOut --[#Green]> mainStorage
mainStorage .[#Red].> mainOut
mainOut --[#Green]> cloud
mainOut --[#Green]> verifier
verifier --[#Green]> ds
ds .[#Red].> verifier
verifier --[#Green]> mainOut

user --> cloud
cloud -..> user

in --[#Green]> out
out --[#Red]> storage
storage .[#Red].> out
out --[#Red]> cloud



@endumls