# Network start этот блок кода должен быть во всех docker-compose.yml файлах
networks:
  kafka-net:
    name: kafka-net
    driver: bridge
# Network end
services:
  Storage:
    image: storage
    build:
      context: ./src
    depends_on:
      - db-storage
    networks:
      - kafka-net
    ports:
      - "8852:8852"

  db-storage:
    container_name: db-storage
    image: postgres:16.1
    networks:
      - kafka-net
    environment:
      POSTGRES_DB: "Storage"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "1234"
    ports:
      - 5433:5432

      
