# Network start этот блок кода должен быть во всех docker-compose.yml файлах
networks:
  kafka-net:
    name: kafka-net
    driver: bridge
# Network end
services:
  mainHub:
    image: main-hub
    build:
      context: ./src
    networks:
      - kafka-net
    ports:
      - "80:80"


      
