# Network start этот блок кода должен быть во всех docker-compose.yml файлах
networks:
  kafka-net:
    name: kafka-net
    driver: bridge
# Network end
services:
  mainStorage:
    image: main-storage
    build:
      context: ./src
    depends_on:
      - db-main-storage
    networks:
      - kafka-net
    ports:
      - "81:81"

  db-main-storage:
    container_name: db-main-storage
    image: postgres:16.1
    networks:
      - kafka-net
    environment:
      POSTGRES_DB: "MainStorage"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "1234"
    ports:
      - 5432:5432

      
