# Network start этот блок кода должен быть во всех docker-compose.yml файлах
networks:
  kafka-net:
    name: kafka-net
    driver: bridge
# Network end
services:
  Hub:
    image: hub
    build:
      context: ./src
    networks:
      - kafka-net
    ports:
      - 8802:8802


      
